title: "❓ Question: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask anything about mcpd — setup, configuration, MCP protocol, hardware compatibility, etc.
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What do you need help with?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What board/setup are you using? Any relevant code or error messages?
      placeholder: "I'm using ESP32 with..."
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - ESP32
        - RP2040 / Pico W
        - Native/Host
        - Other
